apiVersion: batch/v1
kind: CronJob
metadata:
  name: co-pqrs-back-load-seizures-data

  labels:
    app.kubernetes.io/name: co-pqrs-back-load-seizures-data
    app.kubernetes.io/component: batch-loader
    app.kubernetes.io/part-of: jobs
    app.kubernetes.io/version: v2
    app.openshift.io/runtime: python

  annotations:
    app.openshift.io/display-name: "Embargos Loader"

spec:
  schedule: "50 7 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1

      template:
        metadata:
          labels:
            app.kubernetes.io/name: co-pqrs-back-load-seizures-data
            app.kubernetes.io/component: batch-loader
            app.kubernetes.io/part-of: jobs
            app.kubernetes.io/version: v2
            app.openshift.io/runtime: python

          annotations:
            app.openshift.io/display-name: "Embargos Loader"

        spec:
          restartPolicy: Never

          volumes:
            - name: embargos-data
              persistentVolumeClaim:
                claimName: smb-pvc-tx

          containers:
            - name: loader
              image: quay.apps.work.ocp.co.igrupobbva/pqr-genai/co_pqrs_back_load_seizures_data:v1
              imagePullPolicy: Always

              env:
                - name: TZ
                  value: America/Bogota
                - name: DB_HOST
                  value: postgresql.pqr-genai-dev.svc.cluster.local

                - name: DB_PORT
                  value: "5432"

                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRESQL_DATABASE

                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRESQL_USER

                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRESQL_PASSWORD

                - name: RUTA_PROCESO
                  value: /mnt/embargos

                - name: ERROR_HANDLER_SERVICE_URL
                  value: "http://co-pqrs-back-error-handler.pqr-genai-dev.svc.cluster.local:8002"

                - name: CSV_DELIMITER
                  value: ";"

                - name: FILE_ENCODING
                  value: cp1252

                - name: FILE_ENCODING_FALLBACKS
                  value: "latin-1,utf-8"

                - name: CSV_QUOTE_CHAR
                  value: "\u0001"

                - name: CSV_ESCAPE_CHAR
                  value: "\u0001"

              volumeMounts:
                - name: embargos-data
                  mountPath: /mnt/embargos
                  subPath: RECEPCION_HOST/EMBARGOS
                  readOnly: true
