apiVersion: v1
kind: Service
metadata:
  name: co-bucket-concilia
  labels:
    app: co-bucket-concilia
    app.kubernetes.io/name: co-bucket-concilia
    app.kubernetes.io/part-of: bucket
spec:
  selector:
    app: co-bucket-concilia
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
