apiVersion: v1
kind: Service
metadata:
  name: co-backend-concilia
  labels:
    app: co-backend-concilia
    app.kubernetes.io/name: co-backend-concilia
    app.kubernetes.io/part-of: backend
    app.kubernetes.io/component: backend-api
spec:
  selector:
    app: co-backend-concilia
  ports:
    - name: http
      port: 8080
      targetPort: http
