from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class MessageRole(str, Enum):
    """
    Base model to set roles for messages.
    """

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ConversationStatus(str, Enum):
    """
    Allowed lifecycle states for a conversation.
    """

    ACTIVE = "Active"
    RUNNING = "Running"
    INACTIVE = "Inactive"
    CLOSED = "Closed"
    ERROR = "Error"


class TokenUsage(BaseModel):
    """
    Base model to trace tokens in the interactions.
    """

    model_config = ConfigDict(extra="forbid")

    input_tokens: int = Field(
        ge=0,
        description="Number of input tokens sent to the model.",
        examples=[120],
    )
    output_tokens: int = Field(
        ge=0,
        description="Number of output tokens generated by the model.",
        examples=[85],
    )
    total_tokens: int = Field(
        ge=0,
        description="Total token usage for the message interaction.",
        examples=[205],
    )
    cached_input_tokens: int = Field(
        default=0,
        ge=0,
        description=(
            "Portion of `input_tokens` served from the provider's prompt cache. "
            "Azure/OpenAI report it as `prompt_tokens_details.cached_tokens`. It is "
            "a SUBSET of input_tokens, never added on top, so totals stay comparable "
            "with messages stored before this field existed (which default to 0)."
        ),
        examples=[12800],
    )


class MessageTiming(BaseModel):
    """
    Base model to trace timing in the interactions.
    """

    model_config = ConfigDict(extra="forbid")

    received_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the message event started. For user messages it is the arrival time; for assistant messages it is when response generation began.",
    )
    responded_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when processing for the message event finished.",
    )
    total_duration_ms: int | None = Field(
        default=None,
        ge=0,
        description="Total elapsed time in milliseconds between the start and end of the message event.",
        examples=[2750],
    )


class Message(BaseModel):
    """
    Base model to exchange messages with the agent.
    """

    # Base configuration for al fields

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    id: str = Field(
        description="Unique identifier for the message.",
        examples=["msg_001"],
    )

    role: MessageRole = Field(
        description="Sender role within the agent conversation.",
        examples=["user"],
    )

    content: str = Field(
        min_length=1,
        description="Natural language content sent to the agent.",
        examples=["Necesito un resumen del caso."],
    )

    tokens: TokenUsage = Field(
        description="Token usage associated with this message.",
    )

    timing: MessageTiming = Field(
        description="Timing information for traceability.",
    )

    def set_response_time(self, responded_at: datetime | None = None) -> None:
        """
        Set the response timestamp and calculate the total duration in milliseconds.

        Args:
            responded_at: Optional UTC datetime to use as the response time.
                If not provided, the current UTC time is used.
        """

        response_time = responded_at or datetime.now(timezone.utc)

        if response_time.tzinfo is None:
            response_time = response_time.replace(tzinfo=timezone.utc)

        if self.timing.received_at.tzinfo is None:
            self.timing.received_at = self.timing.received_at.replace(
                tzinfo=timezone.utc
            )

        if response_time < self.timing.received_at:
            raise ValueError("responded_at cannot be earlier than received_at")

        duration = response_time - self.timing.received_at

        self.timing.responded_at = response_time
        self.timing.total_duration_ms = int(duration.total_seconds() * 1000)


class Conversation(BaseModel):
    """
    Base model to track conversation state and workflow metadata.
    """

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    conversation_id: str = Field(
        description="Unique identifier for the conversation that groups related messages and agent actions.",
        examples=["conv_123"],
    )

    first_msg_date: datetime | None = Field(
        default=None,
        description="UTC timestamp for when the first message in the conversation was received.",
    )

    last_msg_date: datetime | None = Field(
        default=None,
        description="UTC timestamp for the most recent message or agent response in the conversation.",
    )

    status: ConversationStatus = Field(
        description="Current lifecycle status of the conversation.",
        examples=["Active"],
    )

    running_since: datetime | None = Field(
        default=None,
        description=(
            "UTC timestamp for when the conversation entered the RUNNING state. "
            "Used by the watchdog to auto-recover turns stuck in RUNNING."
        ),
    )

    current_step: str = Field(
        default="0",
        description="Current numeric step being executed within the active workflow.",
        examples=["start", "start.confirmation", "1", "1.2"],
    )

    general_workflow: str | None = Field(
        default=None,
        description="Top-level workflow group selected before entering the specific workflow.",
        examples=["Hazlo tú mismo", "Guía rápida"],
    )

    workflow: str | None = Field(
        default=None,
        description="Business workflow assigned to the conversation, if one was selected.",
        examples=["Riesgo"],
    )

    flow_version: int | None = Field(
        default=None,
        description="Version of the workflow definition currently used by the conversation.",
        examples=[1],
    )

    flow_answers: dict[str, str] = Field(
        default_factory=dict,
        description="Structured answers captured while traversing the workflow steps.",
        examples=[{"request_type": "consulta", "consulta_producto": "cuenta"}],
    )

    captured_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Normalized data extracted from user answers by the agent.",
        examples=[{"consulta_cuenta_detalle": "Quiero saber el saldo de mi cuenta"}],
    )

    satisfaction_status: str | None = Field(
        default=None,
        description="Satisfaction-check lifecycle state. Set to ENTERED when the step is shown; set to ABANDONED by the maintenance flow when the user never responded.",
        examples=["ENTERED", "ABANDONED"],
    )

    satisfaction_result: bool | None = Field(
        default=None,
        description="User response to the satisfaction check. True = Sí (helped), False = No (not helped), None = not answered.",
        examples=[True, False],
    )

    closed_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when the maintenance job closed the conversation.",
    )
    maintenance_locked_by: str | None = Field(
        default=None,
        description="Identifier of the maintenance run that locked the conversation.",
    )
    maintenance_locked_at: datetime | None = Field(
        default=None,
        description="UTC timestamp when the maintenance job locked the conversation.",
    )
    maintenance_export_path: str | None = Field(
        default=None,
        description="Path where the maintenance job exported the conversation.",
    )

    user_id: str = Field(
        description="Unique identifier of the user associated with the conversation.",
        examples=["user_001"],
    )

    messages: list[Message] = Field(
        default_factory=list,
        description="List that contains all the messages of the conversation between agent and user.",
    )

    def add_message(self, message: Message) -> None:
        """
        Append a message to the conversation and update conversation timestamps.

        Args:
            message: Message instance to append to the conversation history.
        """

        self.messages.append(message)
        self.refresh_message_dates()

    def refresh_message_dates(self) -> None:
        """
        Recalculate the first and last conversation timestamps from the message history.
        """

        if not self.messages:
            self.first_msg_date = None
            self.last_msg_date = None
            return

        first_received_at = min(message.timing.received_at for message in self.messages)

        latest_event_at = max(
            message.timing.responded_at or message.timing.received_at
            for message in self.messages
        )

        self.first_msg_date = first_received_at
        self.last_msg_date = latest_event_at
