apiVersion: v1
kind: Service
metadata:
  name: co-pqrs-back-error-handler
  namespace: pqr-genai-dev
  labels:
    app: co-pqrs-back-error-handler
    app.kubernetes.io/part-of: backend
spec:
  selector:
    app: co-pqrs-back-error-handler
  ports:
    - name: http
      port: 8002
      targetPort: http
      protocol: TCP
