version: "9.0.0"
fase: "MVP1"
archivosEsperados: 12
caitEnAlcance: false
modeloDatos:
  tablasFase1: 21
  tablasComunes: 8
  tablasResultado: 13
implementacionPrioritaria: ["HA22","HA26","HA32","CAET","CANT","DEPO","CARTA_COMPENSACION","PMD","MEP","VSS"]
desarrolloFinal: ["PMPD1322","PMRD8000"]
arquitectura:
  orquestador: "Control-M Local Colombia"
  transferencia: "SFTP:22"
  landing: "MinIO/OKD"
