apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-pqr-maintenance-env
  namespace: pqr-genai-dev
  labels:
    app.kubernetes.io/part-of: backend
data:
  .env: |
    OPENSEARCH_HOSTS=https://opensearch.pqr-genai-dev.svc.cluster.local:9200
    OPENSEARCH_USERNAME=admin
    OPENSEARCH_PASSWORD=K9!rT2vQx#7LmP
    OPENSEARCH_VERIFY_CERTS=false
    OPENSEARCH_CONVERSATIONS_INDEX=conversations-reference
    OPENSEARCH_MESSAGES_INDEX=conversations-messages
    OUTPUT_DIR=/app/data
    INACTIVE_MINUTES=5
    CONVERSATION_STATUS_FIELD=status
    ACTIVE_STATUS_VALUE=Active
    CLOSED_STATUS_VALUE=Closed
    CONVERSATION_ID_FIELD=id
    MESSAGE_CONVERSATION_ID_FIELD=conversation_id
    LAST_INTERACTION_FIELDS=last_msg_date,last_interaction_at,updated_at,last_message_at
    MESSAGE_TIMESTAMP_FIELDS=created_at,timestamp,sent_at
    CLOSED_AT_FIELD=closed_at
    EXPORTED_AT_FIELD=maintenance_exported_at
    EXPORTED_PATH_FIELD=maintenance_export_path
    DELETE_EXPORTED_CONVERSATIONS=true
    DELETE_EXPORTED_MESSAGES=true
    DEFAULT_TIMEZONE=America/Bogota
    CRON_SCHEDULE=* * * * *
    OPENSEARCH_CONTROL_INDEX=client-control-table
    MINIO_ENABLED=true
    MINIO_ENDPOINT_URL=http://minio.pqr-genai-dev.svc.cluster.local:9000
    MINIO_BUCKET=pqr-conversations-history
    MINIO_REGION=us-east-1
    MINIO_ADDRESSING_STYLE=path
    ERROR_HANDLER_SERVICE_URL=http://co-pqrs-back-error-handler.pqr-genai-dev.svc.cluster.local:8002