apiVersion: v1
kind: Service
metadata:
  name: co-pqrs-back-maintenance
  namespace: pqr-genai-dev
  labels:
    app: co-pqrs-back-maintenance
    app.kubernetes.io/part-of: backend
spec:
  type: ClusterIP
  selector:
    app: co-pqrs-back-maintenance
    deployment: co-pqrs-back-maintenance
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001
