ALLOWED = {
 "recepcion":{"PENDIENTE_RECEPCION":{"RECIBIENDO","OMITIDO","CANCELADO","EXPIRADO"},"RECIBIENDO":{"RECIBIDO","REINTENTANDO","ERROR_RECEPCION"},"REINTENTANDO":{"RECIBIENDO","ERROR_RECEPCION","CANCELADO"}},
 "validacion":{"NO_INICIADA":{"VALIDANDO","OMITIDO","CANCELADO"},"VALIDANDO":{"VALIDADO","REINTENTANDO","ERROR_VALIDACION"},"REINTENTANDO":{"VALIDANDO","ERROR_VALIDACION","CANCELADO"}},
 "procesamiento":{"NO_INICIADO":{"EN_PROCESO","OMITIDO","CANCELADO"},"EN_PROCESO":{"PROCESADO","REINTENTANDO","ERROR_PROCESAMIENTO"},"REINTENTANDO":{"EN_PROCESO","REPROCESANDO","ERROR_PROCESAMIENTO","CANCELADO"},"REPROCESANDO":{"PROCESADO","ERROR_PROCESAMIENTO","CANCELADO"}},
 "carga":{"NO_INICIADA":{"EN_CARGA","OMITIDO","CANCELADO"},"EN_CARGA":{"CARGADO","REINTENTANDO","ERROR_CARGA"},"REINTENTANDO":{"EN_CARGA","REPROCESANDO","ERROR_CARGA","CANCELADO"},"REPROCESANDO":{"CARGADO","ERROR_CARGA","CANCELADO"}},
}
def ensure_transition(stage,current,target):
    if target not in ALLOWED.get(stage,{}).get(current,set()):
        raise ValueError(f"Transición inválida {stage}: {current} -> {target}")
