apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app.kubernetes.io/part-of: elk-metrics
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch-service.pqr-genai-dev.svc.cluster.local:9200" ]
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
    path.data: /usr/share/kibana/data
    xpack.security.encryptionKey: "supersecretencryptionkeyforsecurity9"
    xpack.encryptedSavedObjects.encryptionKey: "supersecretencryptionkeyforobjects9"
    xpack.reporting.encryptionKey: "supersecretencryptionkeyforreports9"