[project]
name = "co-pqrs-back-doble-cobro"
version = "0.1.0"
description = "Servicio del camino de duplicidad en el cobro o doble cobro."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.135.2",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.2.12",
    "pydantic>=2.12.5",
    "python-dateutil>=2.9.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.35.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.0",
]
