apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-analytics-data
  labels:
    app.kubernetes.io/part-of: elk-metrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 30Gi
