apiVersion: v1
kind: Service
metadata:
  name: concilia-postgres
  labels:
    app: concilia-postgres
    app.kubernetes.io/name: concilia-postgres
    app.kubernetes.io/part-of: database
    app.kubernetes.io/component: database-postgresql
spec:
  selector:
    app: concilia-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
