apiVersion: v1
kind: Service
metadata:
  name: co-db-concilia
  labels:
    app: co-db-concilia
    app.kubernetes.io/name: co-db-concilia
    app.kubernetes.io/part-of: database
    app.kubernetes.io/component: database-postgresql
spec:
  selector:
    app: co-db-concilia
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
