INSERT INTO CON_INSUMO_ESPERADO(FUENTE,TIPO_INSUMO,PATRON_ARCHIVO,FORMATO,ORDEN_VISUAL,ESTADO_DESARROLLO) VALUES
('HOST','PMPD1322','GOF.MP.FISD1.MPD1322.MP132210.MPLC5434.D1%%ODATE','TXT_REPORT',1,'FINAL'),
('HOST','PMRD8000','GOF.MP.FJSD1.MRD8000.MRLS7803.F%%ODATE','TXT_REPORT',2,'FINAL'),
('HOST','HA22','DESCARHA22_*','TXT_PIPE',3,'PRIORITARIO'),('HOST','HA26','DESCARHA26_*','TXT_PIPE',4,'PRIORITARIO'),
('HOST','HA32','DESCARHA32_*','TXT_PIPE',5,'PRIORITARIO'),('CREDIBANCO','CAET','*CAET*','FIXED_WIDTH',6,'PRIORITARIO'),
('CREDIBANCO','CANT','*CANT*','FIXED_WIDTH',7,'PRIORITARIO'),('CREDIBANCO','DEPO','*DEPO*','FIXED_WIDTH',8,'PRIORITARIO'),
('CREDIBANCO','CARTA_COMPENSACION','*.xlsx','XLSX_CEI_240A',9,'PRIORITARIO'),
('REDEBAN','PMD','PMDDetalleTransacciones*.xlsx','XLSX_PMD_DETALLE',10,'PRIORITARIO'),
('REDEBAN','MEP','MEP*.xlsx','XLSX',11,'PRIORITARIO'),('VISA','VSS','VSS*.txt','TXT_VSS',12,'PRIORITARIO')
ON CONFLICT (TIPO_INSUMO) DO UPDATE SET PATRON_ARCHIVO=EXCLUDED.PATRON_ARCHIVO,FORMATO=EXCLUDED.FORMATO,ORDEN_VISUAL=EXCLUDED.ORDEN_VISUAL,ESTADO_DESARROLLO=EXCLUDED.ESTADO_DESARROLLO,ACTIVO=TRUE;
