apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # frontend de PRUEBA (Streamlit) para ejercitar el agente
  - co_pqrs_front_test/01-deployment.yaml
  - co_pqrs_front_test/02-service.yaml
  - co_pqrs_front_test/03-route.yaml
