version: "1.0.0"
archivosEsperados: 12
estado:
  columnas:
    - "Fuente"
    - "Información"
    - "Nombre archivo"
    - "Registros"
    - "Recepción"
    - "Validación"
    - "Procesamiento"
    - "Carga"
    - "Disponibilidad"
    - "Acción"
  acciones:
    - "Detalle"
    - "Ver contenido"
  desktopLaptop: true
contenido:
  pageSize: 30
  dtoEspecificoPorInsumo: true
desarrolloPrioritario:
  - "HA22"
  - "HA26"
  - "HA32"
  - "CAET"
  - "CANT"
  - "DEPO"
  - "CARTA_COMPENSACION"
  - "PMD"
  - "MEP"
  - "VSS"
desarrolloFinal:
  - "PMPD1322"
  - "PMRD8000"
