apiVersion: v1
kind: Service
metadata:
  name: concilia-parseo
  labels:
    app: concilia-parseo
    app.kubernetes.io/name: concilia-parseo
    app.kubernetes.io/part-of: backend
    app.kubernetes.io/component: backend-parseo
spec:
  selector:
    app: concilia-parseo
  ports:
    - name: http
      port: 8081
      targetPort: http
