apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - co-backend-concilia/01-deployment.yaml
  - co-backend-concilia/02-service.yaml
  - co-api-parseo/01-deployment.yaml
  - co-api-parseo/02-service.yaml
