apiVersion: v1
kind: Service
metadata:
  name: co-pqrs-back-trx-noreconocida
  labels:
    app.kubernetes.io/part-of: backend
spec:
  selector:
    app: co-pqrs-back-trx-noreconocida
  ports:
    - name: http
      port: 8004
      targetPort: 8004
  type: ClusterIP