apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: co-pqrs-back-trx-noreconocida
  labels:
    app: co-pqrs-back-trx-noreconocida
    app.kubernetes.io/part-of: backend
spec:
  to:
    kind: Service
    name: co-pqrs-back-trx-noreconocida
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect