services:
  conversation-maintenance-api:
    container_name: co-pqrs-back-maintenance-api
    build:
      context: .
      dockerfile: Containerfile
    image: co-pqrs-back-maintenance:latest
    environment:
      SERVICE_MODE: api
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./output:/app/output
    restart: unless-stopped

  conversation-maintenance-cron:
    container_name: co-pqrs-back-maintenance-cron
    build:
      context: .
      dockerfile: Containerfile
    image: co-pqrs-back-maintenance:latest
    environment:
      SERVICE_MODE: cron
    env_file:
      - .env
    volumes:
      - ./output:/app/output
    restart: unless-stopped
