apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-explicito
  labels:
    app: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/part-of: elk-metrics
    app.kubernetes.io/component: queue-broker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi