services:
  co-pqrs-back-agent:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - BUILD_HTTP_PROXY
        - BUILD_HTTPS_PROXY
        - BUILD_NO_PROXY
    image: co-pqrs-back-agent:local
    container_name: co-pqrs-back-agent
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      OPENSEARCH_ENDPOINT: https://host.containers.internal:9200
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped
