apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  labels:
    app.kubernetes.io/part-of: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: cephfs-sc
  volumeMode: Filesystem