apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql/00-secret-template.yaml
  - postgresql/01-pvc.yaml
  - postgresql/02-deployment.yaml
  - postgresql/03-service.yaml
