apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql-pdb
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: database
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: postgresql
