apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgresql-vpa
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: database
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: postgresql
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: postgresql
        mode: Auto
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 500m
          memory: 1Gi
        maxAllowed:
          cpu: "2"
          memory: 4Gi
