apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    app.kubernetes.io/part-of: elk-metrics
data:
  elasticsearch.yml: |
    cluster.name: "elk-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: true
    xpack.security.http.ssl.enabled: false # Alerta: Se sugiere migrar a true para Producción real
    xpack.security.transport.ssl.enabled: false